[api_config]

[downloaders]
storage_dir = ''

[fansly]
enabled = true
auth_token = 'Mjg3MTYzMjI0ODU0Mzc2NDQ4OjE6MTo4YmU0NTRjM2YwZmY0ZDViZDg5N2E2NTI2NTAwYjU'
ignore_lists = []

[only_fans]
enabled = false
session_token = ''
user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36'
app_token = ''
user_id = ''
cookie = 'csrf=APbr5DX44d53a578066ae49b6e3da5462463e9be; cookiesAccepted=true; __stripe_mid=03075297-cd4d-483f-9be6-94b648f1f062307638; dark_mode=true; wallLayout=grid; auth_id=134682957; sess=eg72nk4881p00l64k47k53kq65; st=a6cc657de9b62baec679d3305dc1371171ea4fb620cfaecb1c244ef9b486a47b; ref_src=https://onlyfans.com/my/chats/chat/26542217; fp=54525a5b56d33e691e134261dd27a103'
ignore_lists = []
